---
- name: Installing Flatpaks
  become: true
  package:
    name: flatpak
    state: present

- name: Add Flathub remote
  become: false
  command: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak apps
  become: false
  flatpak:
    name:
      - io.github.fabrialberio.pinapp
      - com.github.tchx84.Flatseal
    state: present
    method: user
